# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1006, 718)
        MainWindow.setStyleSheet("background-color: rgb(40, 105, 161);\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(MainWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(MainWindow)
        self.widget.setStyleSheet("background-color: rgb(189, 217, 231);\n"
"border-radius: 20px;")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pic_area = QtWidgets.QWidget(self.widget)
        self.pic_area.setObjectName("pic_area")
        self.picture_area = QtWidgets.QVBoxLayout(self.pic_area)
        self.picture_area.setObjectName("picture_area")
        self.graphicsView = QtWidgets.QGraphicsView(self.pic_area)
        self.graphicsView.setStyleSheet("QGraphicsView\n"
"{\n"
"    background-color: rgb(141, 196, 230);\n"
"    border-radius: 20px;\n"
"}\n"
"QScrollBar:vertical\n"
"{\n"
"    width:20px;\n"
"    background:rgb(141, 196, 230);\n"
"    padding-top:20px;\n"
"    padding-bottom:20px;\n"
"    border-radius:10px; \n"
"}\n"
"QScrollBar::handle:vertical\n"
"{\n"
"    width:20px;\n"
"    background:rgb(208, 234, 247);\n"
"    border-radius:10px;   \n"
"    min-height:20px;\n"
"}\n"
"QScrollBar::handle:vertical:hover\n"
"{\n"
"    width:20px;\n"
"    background:rgb(211, 240, 255);\n"
"    border-radius:10px;\n"
"    min-height:20px;\n"
"}\n"
"QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical   \n"
"{\n"
"    background:rgb(141, 196, 230);\n"
"    border-radius:10px; \n"
"}\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"    height:20px;\n"
"    width:20px;\n"
"    border-image:url(:/icons/up.png);\n"
"    border-radius:10px; \n"
"    subcontrol-position:top;\n"
"}\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"    height:20px;\n"
"    width:20px;\n"
"    border-image:url(:/icons/down.png);\n"
"    border-radius:10px; \n"
"    subcontrol-position:bottom;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover\n"
"{\n"
"    height:20px;\n"
"    width:20px;\n"
"    border-image:url(:/icons/up_touch.png);\n"
"    border-radius:10px; \n"
"    subcontrol-position:top;\n"
"}\n"
"QScrollBar::add-line:vertical:hover\n"
"{\n"
"    height:20px;\n"
"    width:20px;\n"
"    border-image:url(:/icons/down_touch.png);\n"
"    border-radius:10px; \n"
"    subcontrol-position:bottom;\n"
"}\n"
"\n"
"QScrollBar:horizontal\n"
"{\n"
"    height:20px;\n"
"    background:rgb(141, 196, 230);\n"
"    padding-left:20px;\n"
"    padding-right:20px;\n"
"    border-radius:10px; \n"
"}\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"    height:20px;\n"
"    background:rgb(208, 234, 247);\n"
"    border-radius:10px;   \n"
"    min-width:20px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover\n"
"{\n"
"    height:20px;\n"
"    background:rgb(211, 240, 255);\n"
"    border-radius:10px;\n"
"    min-width:20px;\n"
"}\n"
"QScrollBar::add-page:horizontal,QScrollBar::sub-page:horizontal   \n"
"{\n"
"    background:rgb(141, 196, 230);\n"
"    border-radius:10px; \n"
"}\n"
"QScrollBar::sub-line:horizontal\n"
"{\n"
"    height:20px;\n"
"    width:20px;\n"
"    border-image:url(:/icons/left.png);\n"
"    border-radius:10px; \n"
"    subcontrol-position:left;\n"
"}\n"
"QScrollBar::add-line:horizontal\n"
"{\n"
"    height:20px;\n"
"    width:20px;\n"
"    border-image:url(:/icons/right.png);\n"
"    border-radius:10px; \n"
"    subcontrol-position:right;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover\n"
"{\n"
"    height:20px;\n"
"    width:20px;\n"
"    border-image:url(:/icons/left_touch.png);\n"
"    border-radius:10px; \n"
"    subcontrol-position:left;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover\n"
"{\n"
"    height:20px;\n"
"    width:20px;\n"
"    border-image:url(:/icons/right_touch.png);\n"
"    border-radius:10px; \n"
"    subcontrol-position:right;\n"
"}")
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.graphicsView.setObjectName("graphicsView")
        self.picture_area.addWidget(self.graphicsView)
        self.button_area = QtWidgets.QHBoxLayout()
        self.button_area.setObjectName("button_area")
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.button_area.addItem(spacerItem)
        self.exit_btn = QtWidgets.QPushButton(self.pic_area)
        self.exit_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.exit_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.exit_btn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.exit_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(208, 234, 247);\n"
"    border-radius: 25px;\n"
"}\n"
"QToolTip\n"
"{\n"
"    color:rgb(40, 105, 161);\n"
"    background-color:rgb(208, 234, 247);\n"
"    border:1px solid rgb(40, 105, 161);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(211, 240, 255);\n"
"    border-radius: 25px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(179, 206, 219);\n"
"    border-radius: 25px;\n"
"    border:1px solid rgb(128, 128, 128);\n"
"}")
        self.exit_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn.setIcon(icon)
        self.exit_btn.setIconSize(QtCore.QSize(32, 32))
        self.exit_btn.setObjectName("exit_btn")
        self.button_area.addWidget(self.exit_btn)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.button_area.addItem(spacerItem1)
        self.minimize_btn = QtWidgets.QPushButton(self.pic_area)
        self.minimize_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.minimize_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.minimize_btn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.minimize_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(208, 234, 247);\n"
"    border-radius: 25px;\n"
"}\n"
"QToolTip\n"
"{\n"
"    color:rgb(40, 105, 161);\n"
"    background-color:rgb(208, 234, 247);\n"
"    border:1px solid rgb(40, 105, 161);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(211, 240, 255);\n"
"    border-radius: 25px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(179, 206, 219);\n"
"    border-radius: 25px;\n"
"    border:1px solid rgb(128, 128, 128);\n"
"}")
        self.minimize_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_btn.setIcon(icon1)
        self.minimize_btn.setIconSize(QtCore.QSize(32, 32))
        self.minimize_btn.setObjectName("minimize_btn")
        self.button_area.addWidget(self.minimize_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.button_area.addItem(spacerItem2)
        self.open_btn = QtWidgets.QPushButton(self.pic_area)
        self.open_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.open_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.open_btn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.open_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(208, 234, 247);\n"
"    border-radius: 25px;\n"
"}\n"
"QToolTip\n"
"{\n"
"    color:rgb(40, 105, 161);\n"
"    background-color:rgb(208, 234, 247);\n"
"    border:1px solid rgb(40, 105, 161);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(211, 240, 255);\n"
"    border-radius: 25px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(179, 206, 219);\n"
"    border-radius: 25px;\n"
"    border:1px solid rgb(128, 128, 128);\n"
"}")
        self.open_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_btn.setIcon(icon2)
        self.open_btn.setIconSize(QtCore.QSize(32, 32))
        self.open_btn.setObjectName("open_btn")
        self.button_area.addWidget(self.open_btn)
        spacerItem3 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.button_area.addItem(spacerItem3)
        self.picture_area.addLayout(self.button_area)
        self.horizontalLayout.addWidget(self.pic_area)
        spacerItem4 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(300, 68))
        self.label.setMaximumSize(QtCore.QSize(300, 68))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/bg.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.model_area = QtWidgets.QWidget(self.widget)
        self.model_area.setStyleSheet("background-color: rgb(141, 196, 230);\n"
"border-radius: 20px;")
        self.model_area.setObjectName("model_area")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.model_area)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.model_3_btn = QtWidgets.QPushButton(self.model_area)
        self.model_3_btn.setMinimumSize(QtCore.QSize(100, 120))
        self.model_3_btn.setMaximumSize(QtCore.QSize(100, 120))
        self.model_3_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(208, 234, 247);\n"
"    border-radius: 20px;\n"
"    color: rgb(40, 105, 161);\n"
"}\n"
"QToolTip\n"
"{\n"
"    color:rgb(40, 105, 161);\n"
"    background-color:rgb(208, 234, 247);\n"
"    border:1px solid rgb(40, 105, 161);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(211, 240, 255);\n"
"    border-radius: 20px;\n"
"    color: rgb(40, 105, 161);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(179, 206, 219);\n"
"    border-radius: 20px;\n"
"    border:1px solid rgb(128, 128, 128);\n"
"    color: rgb(40, 105, 161);\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: rgb(211, 240, 255);\n"
"    border-radius: 20px;\n"
"    color: rgb(40, 105, 161);\n"
"    border:5px solid rgb(40, 105, 161);\n"
"}")
        self.model_3_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/VGGNet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.model_3_btn.setIcon(icon3)
        self.model_3_btn.setIconSize(QtCore.QSize(85, 85))
        self.model_3_btn.setCheckable(True)
        self.model_3_btn.setObjectName("model_3_btn")
        self.gridLayout_3.addWidget(self.model_3_btn, 2, 2, 1, 1)
        self.model_1_btn = QtWidgets.QPushButton(self.model_area)
        self.model_1_btn.setMinimumSize(QtCore.QSize(100, 120))
        self.model_1_btn.setMaximumSize(QtCore.QSize(100, 120))
        self.model_1_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(208, 234, 247);\n"
"    border-radius: 20px;\n"
"    color: rgb(40, 105, 161);\n"
"}\n"
"QToolTip\n"
"{\n"
"    color:rgb(40, 105, 161);\n"
"    background-color:rgb(208, 234, 247);\n"
"    border:1px solid rgb(40, 105, 161);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(211, 240, 255);\n"
"    border-radius: 20px;\n"
"    color: rgb(40, 105, 161);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(179, 206, 219);\n"
"    border-radius: 20px;\n"
"    border:1px solid rgb(128, 128, 128);\n"
"    color: rgb(40, 105, 161);\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: rgb(211, 240, 255);\n"
"    border-radius: 20px;\n"
"    color: rgb(40, 105, 161);\n"
"    border:5px solid rgb(40, 105, 161);\n"
"}")
        self.model_1_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/LeNet-5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.model_1_btn.setIcon(icon4)
        self.model_1_btn.setIconSize(QtCore.QSize(80, 80))
        self.model_1_btn.setCheckable(True)
        self.model_1_btn.setChecked(True)
        self.model_1_btn.setObjectName("model_1_btn")
        self.gridLayout_3.addWidget(self.model_1_btn, 2, 0, 1, 1)
        self.model_2_btn = QtWidgets.QPushButton(self.model_area)
        self.model_2_btn.setMinimumSize(QtCore.QSize(100, 120))
        self.model_2_btn.setMaximumSize(QtCore.QSize(100, 120))
        self.model_2_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(208, 234, 247);\n"
"    border-radius: 20px;\n"
"    color: rgb(40, 105, 161);\n"
"}\n"
"QToolTip\n"
"{\n"
"    color:rgb(40, 105, 161);\n"
"    background-color:rgb(208, 234, 247);\n"
"    border:1px solid rgb(40, 105, 161);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(211, 240, 255);\n"
"    border-radius: 20px;\n"
"    color: rgb(40, 105, 161);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(179, 206, 219);\n"
"    border-radius: 20px;\n"
"    border:1px solid rgb(128, 128, 128);\n"
"    color: rgb(40, 105, 161);\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: rgb(211, 240, 255);\n"
"    border-radius: 20px;\n"
"    color: rgb(40, 105, 161);\n"
"    border:5px solid rgb(40, 105, 161);\n"
"}")
        self.model_2_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/AlexNet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.model_2_btn.setIcon(icon5)
        self.model_2_btn.setIconSize(QtCore.QSize(85, 85))
        self.model_2_btn.setCheckable(True)
        self.model_2_btn.setObjectName("model_2_btn")
        self.gridLayout_3.addWidget(self.model_2_btn, 2, 1, 1, 1)
        self.model_4_btn = QtWidgets.QPushButton(self.model_area)
        self.model_4_btn.setMinimumSize(QtCore.QSize(100, 120))
        self.model_4_btn.setMaximumSize(QtCore.QSize(100, 120))
        self.model_4_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(208, 234, 247);\n"
"    border-radius: 20px;\n"
"    color: rgb(40, 105, 161);\n"
"}\n"
"QToolTip\n"
"{\n"
"    color:rgb(40, 105, 161);\n"
"    background-color:rgb(208, 234, 247);\n"
"    border:1px solid rgb(40, 105, 161);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(211, 240, 255);\n"
"    border-radius: 20px;\n"
"    color: rgb(40, 105, 161);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(179, 206, 219);\n"
"    border-radius: 20px;\n"
"    border:1px solid rgb(128, 128, 128);\n"
"    color: rgb(40, 105, 161);\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: rgb(211, 240, 255);\n"
"    border-radius: 20px;\n"
"    color: rgb(40, 105, 161);\n"
"    border:5px solid rgb(40, 105, 161);\n"
"}")
        self.model_4_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/GoogLenet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.model_4_btn.setIcon(icon6)
        self.model_4_btn.setIconSize(QtCore.QSize(90, 90))
        self.model_4_btn.setCheckable(True)
        self.model_4_btn.setObjectName("model_4_btn")
        self.gridLayout_3.addWidget(self.model_4_btn, 3, 0, 1, 1)
        self.model_5_btn = QtWidgets.QPushButton(self.model_area)
        self.model_5_btn.setMinimumSize(QtCore.QSize(100, 120))
        self.model_5_btn.setMaximumSize(QtCore.QSize(100, 120))
        self.model_5_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(208, 234, 247);\n"
"    border-radius: 20px;\n"
"    color: rgb(40, 105, 161);\n"
"}\n"
"QToolTip\n"
"{\n"
"    color:rgb(40, 105, 161);\n"
"    background-color:rgb(208, 234, 247);\n"
"    border:1px solid rgb(40, 105, 161);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(211, 240, 255);\n"
"    border-radius: 20px;\n"
"    color: rgb(40, 105, 161);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(179, 206, 219);\n"
"    border-radius: 20px;\n"
"    border:1px solid rgb(128, 128, 128);\n"
"    color: rgb(40, 105, 161);\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: rgb(211, 240, 255);\n"
"    border-radius: 20px;\n"
"    color: rgb(40, 105, 161);\n"
"    border:5px solid rgb(40, 105, 161);\n"
"}")
        self.model_5_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/ResNet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.model_5_btn.setIcon(icon7)
        self.model_5_btn.setIconSize(QtCore.QSize(85, 85))
        self.model_5_btn.setCheckable(True)
        self.model_5_btn.setObjectName("model_5_btn")
        self.gridLayout_3.addWidget(self.model_5_btn, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.model_area)
        self.result_area = QtWidgets.QWidget(self.widget)
        self.result_area.setStyleSheet("background-color: rgb(141, 196, 230);\n"
"border-radius: 20px;")
        self.result_area.setObjectName("result_area")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.result_area)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.label_2 = QtWidgets.QLabel(self.result_area)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(40, 105, 161);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.result_label = QtWidgets.QLabel(self.result_area)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.result_label.setFont(font)
        self.result_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.result_label.setStyleSheet("color: rgb(40, 105, 161);")
        self.result_label.setObjectName("result_label")
        self.horizontalLayout_6.addWidget(self.result_label)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.predict_btn = QtWidgets.QPushButton(self.result_area)
        self.predict_btn.setMinimumSize(QtCore.QSize(140, 60))
        self.predict_btn.setMaximumSize(QtCore.QSize(140, 60))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.predict_btn.setFont(font)
        self.predict_btn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.predict_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.predict_btn.setAutoFillBackground(False)
        self.predict_btn.setStyleSheet("QPushButton{\n"
"color: rgb(40, 105, 161);\n"
"border-radius: 20px;\n"
"background-color: rgb(208, 234, 247);\n"
"padding:12px;\n"
"text-align:center;\n"
"}\n"
"QToolTip\n"
"{\n"
"    color:rgb(40, 105, 161);\n"
"    background-color:rgb(208, 234, 247);\n"
"    border:1px solid rgb(40, 105, 161);\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(40, 105, 161);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(211, 240, 255);\n"
"    padding:12px;\n"
"    text-align:center;\n"
"}\n"
"QPushButton:pressed {\n"
"    color: rgb(40, 105, 161);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(179, 206, 219);\n"
"    padding:12px;\n"
"    text-align:center;\n"
"    border:1px solid rgb(128, 128, 128);\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/predict.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.predict_btn.setIcon(icon8)
        self.predict_btn.setIconSize(QtCore.QSize(32, 32))
        self.predict_btn.setObjectName("predict_btn")
        self.horizontalLayout_4.addWidget(self.predict_btn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.result_area)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.widget, 1, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 1, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem10, 0, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 1, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem12, 2, 1, 1, 1)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form"))
        self.label_2.setText(_translate("MainWindow", "分类结果："))
        self.result_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">？</span></p></body></html>"))
        self.predict_btn.setText(_translate("MainWindow", " 分类"))
import resource_rc
